### ISSUE TITLE
Dual screen doesn't work

### ISSUE THREAD

**Issue by fschon** [geovens/gInk#101]
Hi. 

I am using a dual screen setup and the g-ink pen doesn't work properly on the screen screen. The attached image is of a pen drawing a horizontal line across the desktop. At about 2/3 across the pen suddenly jumps up and to the left and then carries on drawing.

The same problem occurs when dragging the g-ink toolbar across to the second screen. it is not possible to pass the magical boundary.

![image](https://user-images.githubusercontent.com/18084317/108062480-21b7e700-705a-11eb-8d85-c77701999f66.png)

**Comment by pubpub-zz** [comment]
Can you try with my fork:
https://github.com/pubpub-zz/ppInk
I'm working regularly with multiple screen successfully

**Comment by geovens** [comment]
Hi,

Please check whether the following tip is relevent and let me know:

There is a known issue for multiple displays of unmatched DPI settings (100%, 125%, 150%, etc.). If you use gInk on a computer with multiple displays of unmatched DPI settings, or you encounter problems such as incorrect snapshot area, being unable to drag toolbar to locations etc., please do the following as a workaround (in Windows 10 version 1903 as an example): right-click gInk.exe, Properties, Compatibility, Change high DPI settings, Enable override high DPI scaling behavior scaling performed by: Application. (do this only for gInk version v1.1.0 and after)

**Comment by fschon** [comment]
Thanks :-) Works perfectly now.
