### ISSUE TITLE
Thanks for the good MIT licensed program

### ISSUE THREAD

**Issue by mrkaban** [geovens/gInk#117]
Hello, thank you very much for a good program under the free MIT license!

I checked the functionality of the program and added it to a large Russian-language portal about free software for Windows, [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/gink-sozdanie-annotacij-na-ekrane/).

**Comment by geovens** [comment]
Thank you for the link!

**Comment by bjones1** [comment]
I agree -- this is a great tool. Thanks for the time you've dedicated to creating it!
