### ISSUE TITLE
Support Wintab

### ISSUE THREAD

**Issue by xue-blood** [geovens/gInk#131]
Thank you very much for write this program. It's so useful and awasome.
I use krita for digit painting, and use wintab for pen input.
Can you make a support of wintab. 
Thanks a lot.

**Comment by pubpub-zz** [comment]
Hi @xue-blood,
can you check my fork : 
https://github.com/pubpub-zz/ppInk
I did check Wacom tablet successfully

**Comment by xue-blood** [comment]
> Hi @xue-blood, can you check my fork : https://github.com/pubpub-zz/ppInk I did check Wacom tablet successfully

Hello @pubpub-zz ,
Thanks for you reply,
I try you fork, and there are so many enhance change.And Wacom does work fine.
There is a switch name as `Use Windows Ink` in Wacom Control Panel.
When check on the pen pressure will take effect.
But It not so good for painting, because it actions more touch than pen.
If we disable it, the Wacom driver will provide pen message by `wintab`.
I found a repository https://github.com/vvvv/WintabDN does the dotnet binding. 
I don't need this very much if bother you.

**Comment by pubpub-zz** [comment]
Unfortunately, both ppInk and gInk uses microsoft ink program not only to collect events but for the global drawing, data analysis,... wintab only provides pen input event collection.
for my knowledge can you clarify/illustrates what does mean  "it actions more touch than pen".

**Comment by xue-blood** [comment]
![2021-10-02 21-42-05](https://user-images.githubusercontent.com/18024882/135720273-6ad17fd0-550f-4352-8b10-902d35383b77.gif)
Oh I see.
Yes wintab only has pen input event, and it just like a mouse with pressure.
Here I had take a screenshot of browser.
If use windows ink, when you drag pen, it will drag view.
And you need long press to select text in window.
So It seem as using finger to touch the screen.

**Comment by pubpub-zz** [comment]
I see, but what are the bad behaviors you are getting witihin ppInk when `use window ink` is checked ?

**Comment by xue-blood** [comment]
Oh,thanks a lot. This is what I want.
And there is no any bad behaviors in ppInk.
Becaus I only use pen and keyboad, and some applications dont support windows ink well. So I set wacom to use wintab default.
Dear friend,I am glad for you to help me, thank u very much.

**Comment by pubpub-zz** [comment]
Happy you enjoy.
Do not hesitate to star ppInk  😉

**Comment by xue-blood** [comment]
Yes,ppInk is perfect.
It make a great helpful for me to taking note on the screen. =￣ω￣=
