### ISSUE TITLE
Proposed Option:AutoClose after snapshot

### ISSUE THREAD

**Issue by pubpub-zz** [geovens/gInk#14]
In order to reduce operator actions, I prefer to close immediately after snapshot. In order to leave everyone to choose the option or not, I've added an option.
[AutoClose.zip](https://github.com/geovens/gInk/files/2377061/AutoClose.zip)

**Comment by geovens** [comment]
Hi pubpub-zz,

Thank you very much for your contribution. I think it's a good idea to provide an option to immediately close the tool bar after snapshot for who need it. I merged the core of your code.

I prefer a simple and brainless interface, including the interface for options, even if that means not providing optimal convenience to all users. So I prefer to not include the option in the Options window. Anyone want to enable this can do it manually in the config.ini file.
