### ISSUE TITLE
Would love to see more hotkeys for different pens

### ISSUE THREAD

**Issue by eokenned** [geovens/gInk#15]
I love this program. Really great work. I'd love to see more hotkeys for different pens. This way I could associate the hotkeys with different buttons on my graphics tablet and pen.

I record screen grab videos for my students. When I want to focus in on something I click a button on my pen - gink comes up via the hotkey. I hightlight/illustrate the point and then switch off with the other button.

I love that the menu at the bottom is discreet. I'd like to hide it altogether if I could.

Thanks - great work

**Comment by geovens** [comment]
Hi eokenned,

Number keys are used to select pens, 'e' is used to select eraser, 'Ctrl + s' is to snapshot, 'Ctrl + d' is to delete all inks, 'Ctrl + z' is to undo. Do these work for you?

**Comment by mavrik** [comment]
Wow...love this program even more now. Perhaps this could be documented in the application itself somewhere as well as the README.

**Comment by geovens** [comment]
In the new version (v0.6.0) there are options for hotkeys now, and the hotkeys could work while in mouse pointer mode if this is enabled. I think you can just dock the toolbar and work only with the hotkeys now.
