### ISSUE TITLE
glnk Needs .NET Framework 3.5 to Work with Windows 10

### ISSUE THREAD

**Issue by u20220123** [geovens/gInk#153]
Hello,

I am trying to use the glnk app (I am using Windows 10 OS), and after I unpacked the zip file to C:\Users\someuser\AppData\Local\gInk_v1.1.0 I got the requirement's prompt for .NET Framework 3.5

The image below illustrates what I am experiencing:

![glnk trying to use the portable version BUT requirement NET Framework - 20220223T114500PST](https://user-images.githubusercontent.com/100314750/155398267-aae88358-5561-46f2-b9b3-8e3d55c313af.png)

Could I get some feedback about this requirement?

Thanks

**Comment by geovens** [comment]
Yeah gInk needs .NET 3.5 and you could just install that as shown in your picture.

**Comment by u20220123** [comment]
@geovens A hopeful question I guess... When you write "you could just install that as shown in your picture" do you mean I can skip the installation of .NET Framework 3.5?

Thanks

**Comment by geovens** [comment]
Hi,
I believe that, currently you have to install .NET Framework 3.5 for gInk to work. If you skip the installation of .NET Framework 3.5, gInk probably will not work at all. I'm not sure though.

**Comment by u20220123** [comment]
I confirm; glnk does not work without installing the .NET Framework

Thanks
