### ISSUE TITLE
Problem with Pointer Mode

### ISSUE THREAD

**Issue by pubpub-zz** [geovens/gInk#17]
Hi Geovens,
    I've met an issue with the pointer mode : when activated, selections of the pens to exit the mode was not possible. I've found the following fixe: in Root.cs:
		public void Pointer()
		{
			if (PointerMode == true)
				return;
			PointerMode = true;
			FormCollection.ToThrough();
			FormButtonHitter.Show();
            **FormButtonHitter.ToTopMost(); //added**
		}

**Comment by geovens** [comment]
Thanks for the report, but I haven't understood your description of the problem. Do you mean that, when you are in the pointer mode, nothings happens if you click on pen icons, thus you are stuck in the pointer mode and not able to switch to pen drawing mode? I can't reproduce this problem. Maybe it occurs under certain circumstances that I don't know.
According to another issue you posted, I believe that you are working on your own fork of this software? Could you confirm that this problem also occurs in the v0.5.3 release version?

**Comment by kaikaiiiiiii** [comment]
> Thanks for the report, but I haven't understood your description of the problem. Do you mean that, when you are in the pointer mode, nothings happens if you click on pen icons, thus you are stuck in the pointer mode and not able to switch to pen drawing mode? I can't reproduce this problem. Maybe it occurs under certain circumstances that I don't know.
> According to another issue you posted, I believe that you are working on your own fork of this software? Could you confirm that this problem also occurs in the v0.5.3 release version?

I get the same problem, exactly as what you described. Just like click action just go through the gink panel. I can only right click to tray icon, exit and restart.

Windows 10 1709 64bit, gink 0.53, dual screen. Yet I'm still trying to find out which occurs the conflict.

**Comment by pubpub-zz** [comment]
Originally the problem was also met on dual screen display. Redoing tests on latest 5.3 on single screen , It looks that like the problem seems also random in this single screen configuation.. Also, based on the fact that  kaikaiiiiiii had to had an extra modification. On 5.3 official, running in Debug Mode on a single FullHD screen at the end of the pointer Function, I'm getting FormButtonHitter.Left = 1920 , which means it is out of screen, but when I enter Unpointer clicking on a color pen, I get FormButtonHitter.Left = 1194. Could the problem be linked with the computation of the position of the FormButtonHitter ?

**Comment by clay584** [comment]
I am also experiencing this issue. Once in click-through mode, I cannot click to get back to drawing mode. Therefore I am stuck, and must click the tray icon and exit the program entirely. Windows 10 with three monitors.

**Comment by geovens** [comment]
Hi all,

Could you try this version and see if it fixed the issue? [gInk_v0.5.4rc1.zip](https://github.com/geovens/gInk/files/2674946/gInk_v0.5.4rc1.zip)

I think I fixed a button position related bug under some multiple screen settings, but according to your descriptions there might be another problem I still don't know.

**Comment by robwein** [comment]
Hi all,

it seems that the problem is solved. **gInk_v0.5.4rc1** works fine for me on Win10 with two monitors.

**Comment by kaikaiiiiiii** [comment]
> Hi all,
> 
> Could you try this version and see if it fixed the issue? [gInk_v0.5.4rc1.zip](https://github.com/geovens/gInk/files/2674946/gInk_v0.5.4rc1.zip)
> 
> I think I fixed a button position related bug under some multiple screen settings, but according to your descriptions there might be another problem I still don't know.

**gInk_v0.5.4rc1** works fine for me too, on Win10 dual screen.

**Comment by clay584** [comment]
This fixed the problem for me! Thank you.
