### ISSUE TITLE
Text feature request 

### ISSUE THREAD

**Issue by Myles-Kadusale-Golden** [geovens/gInk#177]
Hello
First I would like to thank all the contributors for this wonderful and useful application.
I just would like to request if possible can you please add a feature to add text in the screen.

Thanks Again

**Comment by pubpub-zz** [comment]
@Myles-Kadusale-Golden, you may be interested in having a look at https://github.com/pubpub-zz/ppInk. I've introduced Text typing capability

**Comment by Myles-Kadusale-Golden** [comment]
Thanks @pubpub-zz  will check it out

**Comment by pubpub-zz** [comment]
@Myles-Kadusale-Golden, do not hesitate to star ppInk if you like it 😉

**Comment by Myles-Kadusale-Golden** [comment]
@pubpub-zz  done adding stars thanks for your great effort
