### ISSUE TITLE
Can't erase when using Windows Ink, no pen pressure when not using Windows Ink

### ISSUE THREAD

**Issue by kohanyirobert** [geovens/gInk#18]
Well, the issue is in the title basically, but here's more input: I'm using gInk 0.5.2. I have a Wacom Intuos S tablet with the latest drivers. In the tablet properties menu I can enable/disable Windows Ink.

However, if I disable Windows Ink everything works okay *except* pen pressure.
If I enable Windows Ink everything seems to be working, but if I select the eraser and try to erase something I'm actually drawing.

I figure this isn't a particular problem rooted in gInk, but there are apps that can work around this. Corel Painter for example: I use it without Windows Ink enabled, but pen pressure still works.

My goal is: be able to erase and have pen pressue in gInk :) Very cool app by the way!

Edit.:

Hmm, I've noticed something: when Windows Ink enabled, I draw something. Then with the pen (this is important) I click on the eraser. I try to erase, doesn't work. Then with the mouse now I click on the eraser and try to erase. It works. If I use my pen and try to erase it still doesn't work.

**Comment by geovens** [comment]
Thank you for the detailed report. Have you tried v0.5.3? I don't have a Wacom so I can't try it out, but I believe that v0.5.3 should have fixed the eraser when Windows Ink are enabled.

**Comment by kohanyirobert** [comment]
Yay! Works like a charm! Thanks! :)
