### ISSUE TITLE
Previously drawn lines modified when new lines drawn

### ISSUE THREAD

**Issue by kohanyirobert** [geovens/gInk#19]
I'm using gInk v0.5.3 now, but the thing I'm describing was the same in v0.5.2 too. Whether Windows Ink is being used or not doesn't make any difference.

I'm made two pictures (see below) to illustrate what's happening, between two strokes. Please notice that in the first picture there are 3 strokes. In the second I draw another one, the bottom one. Then also notice that the third stroke from the top gets lengthened somewhat. I hope it makes sense. If you download the images and step back and forth between them it'll be visible (I couldn't make a video, because only a white background is captured).

I'm not sure why is this. If I just start drawing like mad sometimes the very first strokes I've drawn are modified (not necessarily in parallel direction, I think it has to do with the direction of the last line drawn).

![a](https://user-images.githubusercontent.com/1104829/47132245-48578e80-d2a3-11e8-8057-c3f64cf139fb.png)
![b](https://user-images.githubusercontent.com/1104829/47132250-4a215200-d2a3-11e8-8f26-fc9a2f3b4e63.png)

**Comment by geovens** [comment]
I believe this has been fixed in the new version (0.6.0).
