### ISSUE TITLE
[feat] No need to show tool bar

### ISSUE THREAD

**Issue by Arslan2214** [geovens/gInk#220]
Why not to add some mode of feature that enable to use all tools without displaying any toolbar.

## What problem I face?
I was giving online classes to some of my students and at that time some times it is too frustrating that toolbar cover some part of screen, Then I thought that there should be some auto hotkeys like feature that enables user to use all tools without explicitly selecting tools.

## Some Suggestion
You can add some hotkeys that triggers various features, I this sense user can user tool different tools without being frustrated to move mouse towards toolbar every time he want to select some tool.

At the moment, I'm moving to some other tools like **ZoomIt**, That provide this feature and look forward for your upgradation in feature.

**Comment by pubpub-zz** [comment]
you shoud check in config.ini:
```
# Whether to hide the toolbar completely
# If Always_Hide_Toolbar = True, the toolbar will never be shown. You will have to use hotkeys.
Always_Hide_Toolbar = False
```

**Comment by Arslan2214** [comment]
That really helps **Thanks For Help...💕**
