### ISSUE TITLE
Hotkey for entering and Exiting Mouse Pointer Mode

### ISSUE THREAD

**Issue by mavrik** [geovens/gInk#23]
Great program geovens!

There seems to be no hotkey for entering the mouse pointer mode. Also, after once entering the pointer mode, the hotkeys for the various pens do not work. Perhaps Ctrl+Alt+G would be a good candidate.

**Comment by denutza** [comment]
Are there now hotkeys for entering and exiting draw mode so we never have to see the bar for presentations?

**Comment by kurt-o-sys** [comment]
+1

Great application, right, but having hotkeys for the pens/eraser/drawing-or-pointer-mode would be really nice!

**Comment by geovens** [comment]
In the new version (0.6.0) the global hotkey (the default Ctrl+Alt+G one) switches mouse pointer mode and drawing mode. There are also hotkey options for pens and tools, and the hotkeys could also work in mouse pointer mode.
