### ISSUE TITLE
Screen Clip doesn't clip the right area

### ISSUE THREAD

**Issue by MarcusAurelio** [geovens/gInk#3]
On larger resolutions the screen clipping doesn't clip the right area. 

If I select an area on the screen, it clips the wrong side of the screen.

**Comment by geovens** [comment]
Hey MarcusAurelio!

Thanks for your interest in my program. It's indeed a pleasant surprise to me that someone would come to this as I never advertised it. Could you provide a bit more information about your system version and resolution?

If, just in case, that you happen to be using a different DPI setting other than 100% (e.g. 125%, 150%, 175%, etc.), you could try whether disabling display scaling on high DPI settings for gInk.exe (right click on gInk.exe -> Properties -> Compatibility -> Disable display scaling on high DPI settings) could solve the problem, as this is a know fact that could cause incorrect clipping area. 

Thank you!

**Comment by MarcusAurelio** [comment]
That solved it. Thank you.

It's a great app - I really like that you have made this Open Source. I have noticed that when the screenshot takes place it wipes the screen drawing out. Is this by design?

For instance - I am a designer that makes notes on screens, I clip a screen area and want to send it to a friend with my written notes. As soon as I hit the screenshot - it seems to wipe or delete all my other screen writing. Is there a way to maintain the screen draws after a screenshot is taken?

**Comment by geovens** [comment]
Hi,
In the new version (0.3.3) the screen draws won't disappear any more after taking a screenshot :)
Thank you!

**Comment by MarcusAurelio** [comment]
Nice!

I will keep testing it out and let you know if I find new bugs.

**Comment by geovens** [comment]
This should have been fully fixed in v0.4.0, not requiring the workaround of disabling high DPI setting.
Though disabling high DPI setting is still recommended as the inks look better to me...
