### ISSUE TITLE
gInk dashboard still erases drawing ontop of default dashboard size after buttons have been removed

### ISSUE THREAD

**Issue by Jivvy** [geovens/gInk#31]
![image](https://user-images.githubusercontent.com/24281896/60069564-f04a1500-96d8-11e9-86d9-27f846115b9a.png)

As shown in image, drawing is erased even when size of gInk dashboard is smaller due to disabling certain buttons in options.

**Comment by geovens** [comment]
I think I have fixed this in 0.6.0.
