### ISSUE TITLE
change palette location

### ISSUE THREAD

**Issue by j2l** [geovens/gInk#33]
Wonderful!

Is there a way to change the palette location?

Because my taskbar is top of my screen and gInk palette is at bottom and partial outside the screen:
![image](https://user-images.githubusercontent.com/65325/60339384-ea8a5300-99a8-11e9-84f2-eca1dde3e3e9.png)

I checked config.ini but didn't find any option to change it.

**Comment by Jivvy** [comment]
I just added this, @j2l . #30

**Comment by geovens** [comment]
In the new beta version 0.6.0, the default location of the palette should have been fix when taskbar is on top. Dragging the palette is also implemented which can be enabled in the Options Window, but this is experimental.

**Comment by j2l** [comment]
Sounds great, thanks!
