### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by tiborepcek** [geovens/gInk#35]
Hi, is it possible to translate gInk into different languages?

I would like to contribute with slovak language.

Thanks.

**Comment by geovens** [comment]
Thanks. I will add language files, but maybe at a month later, depending whether I find spare time.

**Comment by geovens** [comment]
gInk v1.0.0 supports translation now. Here is how you can contribute translation. Simply create a duplication of the file "en-us.txt" in "lang" folder, rename it (to something like "sk.txt") and then translate the strings in the file. The first line in the file is the language name in native. You can check in gInk to make sure your translation shows correctly, and then you can make a pull request to merge your translation to the next version of release for others to use.

**Comment by tiborepcek** [comment]
Thank you. I added [PR with my slovak lng file](https://github.com/geovens/gInk/pull/36) and realized, there are [few glitches in translation](https://github.com/geovens/gInk/issues/37).
