### ISSUE TITLE
Option to hide toolbar completely

### ISSUE THREAD

**Issue by StianOby** [geovens/gInk#38]
I often use gInk as a screen annotation tool when creating educational videos for law students (I am an Associate Professor at the University of Oslo Faculty of Law). I capture the entire screen, and annotate digital documents (cases, statutes, etc). This works well, but I am a bit annoyed about the fact that it impossible to completely hide the gInk toolbar. I can collapse it, but the small arrow icon persists.

As a new feature, I therefore suggest an option to hide the panel completely. (It is still possible to use all gInk features with a hidden panel, through hotkeys.)

**Comment by geovens** [comment]
I guess it's too late but in the next version, in config.ini, you can find a line
> Always_Hide_Toolbar = False
As the name suggests, if you change the value from False to True, the toolbar will always be invisible no matter what. This option can only be found in config.ini, not in the options window.

**Comment by StianOby** [comment]
It's never too late for good features. Thanks for implementing!
