### ISSUE TITLE
Shortcut to open the tools menu

### ISSUE THREAD

**Issue by MarcusAurelio** [geovens/gInk#4]
It would be great to hit 'CTRL + D' to launch the tool menu. Right now you have to click the tray icon to launch the tools menu.

Also, it would be great to have a setting that automatically saves screenshots to a directory specified. For instance - Screen clip and area, then hit "ALT + S". Which automatically saves that clip to the specified directory.

The two features are what is limited in Epic Pen.

**Comment by geovens** [comment]
Hi MarcusAurelio!

The default hotkey to launch the tool menu is Ctrl + Alt + G, and you can change it in config.ini.

Saving snapshots to the disk sounds like a feature that will be requested by a large portion of users, so I think I should do it. What do you think if I create a "snapshots" folder under the application folder and save the snapshots there by default, while the path could be changed in config.ini? 

I think that I might introduce an UI for these settings someday.

Thank you.

**Comment by MarcusAurelio** [comment]
That's a great idea. Microsoft had a small tool in one of their SDKs that allowed you to save and share screenshots. Take this Use Case:

A software tester notices a mistake in the UI of the company software. The software tester writes up notes on screen, takes a snapshot using Gink which is automatically saved to a directory of choice. This directory can be a shared directory like Dropbox, Google Drive, TFS shared drive, FTP.. which automatically gets synched across to other users.

I think you could have two options; one to save to the clipboard (for copy paste) and one to store the aforementioned screen grab to a directory.

I think unlike Epic Pen, this will become a really useful professional tool.

**Comment by geovens** [comment]
In v0.4.0 the screenshots are saved as .jpg files, in "Pictures\gInk" folder (of the current Windows user) by default. Currently the save location can be changed in config.ini.
