### ISSUE TITLE
Global Hotkey Add's "+ Alt every time the app is closed and reopened

### ISSUE THREAD

**Issue by russell359** [geovens/gInk#43]
I want the global hotkey to be Ctrl + Shift + Z but after the app is closed and reopens it reverts to Ctrl + Shift + Alt + Z, I tried replacing Z with another letter, such as Q but the Alt key still gets re-added. I've had no problems with hotkeys for the other options reverting, just seems to be the global hotkey.

**Comment by geovens** [comment]
Hi, I think I fixed this bug in v1.0.3.

**Comment by russell359** [comment]
Thank you very much, I can confirm it's fixed my end too.
