### ISSUE TITLE
German language

### ISSUE THREAD

**Issue by Astrosniky** [geovens/gInk#53]
Please add German language. 

LanguageName = "German"

ButtonNamePen0 = "Stift 0"
ButtonNamePen1 = "Stift 1"
ButtonNamePen2 = "Stift 2"
ButtonNamePen3 = "Stift 3"
ButtonNamePen4 = "Stift 4"
ButtonNamePen5 = "Stift 5"
ButtonNamePen6 = "Stift 6"
ButtonNamePen7 = "Stift 7"
ButtonNamePen8 = "Stift 8"
ButtonNamePen9 = "Stift 9"

ButtonNamePenwidth = "Stiftbreite"
ButtonNameErasor = "Radierer"
ButtonNamePan = "Verschieben"
ButtonNameMousePointer = "Mauszeiger"
ButtonNameInkVisible = "Farbe sichtbar"
ButtonNameSnapshot = "Screenshot"
ButtonNameUndo = "Rückgängig"
ButtonNameRedo = "Wiederholen"
ButtonNameClear = "Alles löschen"
ButtonNameExit = "Werkzeugleiste schließen"
ButtonNameDock = "Werkzeugleiste ausklappen/einklappen"

MenuEntryExit = "Beenden"
MenuEntryOptions = "Optionen"
MenuEntryAbout = "Über"

OptionsTabGeneral = "Allgemein"
OptionsTabPens = "Stifte"
OptionsTabHotkeys = "Tastenkombinationen"

OptionsGeneralLanguage = "Sprache"
OptionsGeneralCanvascursor = "Zeichenmausanzeige"
OptionsGeneralCanvascursorArrow = "Pfeil"
OptionsGeneralCanvascursorPentip = "Stiftspitze"
OptionsGeneralSnapshotsavepath = "Speicherort für Screenshots"
OptionsGeneralWhitetrayicon = "Weißes Taskleistenicon verwenden"
OptionsGeneralAllowdragging = "Verschieben der Werkzeugleiste erlauben"
OptionsGeneralNotePenwidth = "Beachte: Stiftbreitenfeld überschreibt alle individuellen Stiftbreiteneinstellungen"

OptionsPensShow = "Zeigen"
OptionsPensColor = "Farbe"
OptionsPensAlpha = "Transparenz"
OptionsPensWidth = "Breite"
OptionsPensPencil = "Farbstift"
OptionsPensHighlighter = "Textmarker"
OptionsPensThin = "Dünn"
OptionsPensNormal = "Normal"
OptionsPensThick = "Dick"

OptionsHotkeysglobal = "Zentrale Tastenkombination (Zeichnen starten, Wechseln zwischen Mauszeiger und Zeichnen)"
OptionsHotkeysEnableinpointer = "Im Mauszeigermodus folgende Tastenkombinationen erlauben (kann Probleme verursachen)"

NotificationSnapshot = "Screenshot gespeichert. Hier klicken um auszuwählen."

**Comment by geovens** [comment]
Thank you!

**Comment by Astrosniky** [comment]
Thank you for this project! 

I tried to post the language file but when I checked it in gInk there are some character problems (please look at the snapshot). I'm so interest in how you solve such display/language specific problems fundamentally!??? Program code??? I think of Chinese Charakters also/especially... I really want to know/learn. 
Thank you so much for your answer.

Timo

--
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.

 
  
  
 
 Am 16.01.20, 01:35 schrieb Weizhi Nai <notifications@github.com>:

  Thank you!

**Comment by Astrosniky** [comment]
![Screenhot_gInk](https://user-images.githubusercontent.com/59938569/72545415-47882080-3889-11ea-9fe2-7c65c1399386.png)
This is the snapshot...

**Comment by Astrosniky** [comment]
The problem was my editor (not UTF-8). Now here is the correctly file:
[ger.txt](https://github.com/geovens/gInk/files/4074116/ger.txt)
