### ISSUE TITLE
Tool-bar disappears after taking screen shot

### ISSUE THREAD

**Issue by reactofx** [geovens/gInk#58]
Every time I take a screen shot the folded tool-bar  disappears.

**Comment by geovens** [comment]
Currently it is expected to behave in this way:

1. After taking a screen shot without having drawn any ink on the screen, the toolbar closes itself.
2. After taking a screen shot with some inks on the screen, the toolbar does not close itself.
3. If you have changed the Close_On_Snap setting to True in config.ini, after taking a screen shot the toolbar always closes itself, no matter whether there is ink on the screen or not.

Does this behave the same way for you?

**Comment by reactofx** [comment]
Good morning geovens,

Thanks for your swift response, much appreciated.
 
The program behaves according to your description. Can I make a change in config.ini so the tool-bar will always stay on the screen after taking a screen shot?
If not, would you please consider building the option in the program. Because the tool-bar folds, it can stay on without being in the way, a very strong point.

 Best regards, Robert

**Comment by geovens** [comment]
Not possible currently, but OK, I think I will change the program so that if you set Close_On_Snap to False in config.ini it will not close itself no matter what.

**Comment by geovens** [comment]
In next version, in config.ini, you can find a line
> Close_On_Snap = BlankOnly

If you change the value from BlankOnly to False, the toolbar will not close itself after a screenshot no matter what. This option can only be found in config.ini, not in the options window.
