### ISSUE TITLE
Crash on Windows 10

### ISSUE THREAD

**Issue by szevzol** [geovens/gInk#65]
I got a crash on every start.

Operating system is Windows 10

![image](https://user-images.githubusercontent.com/3088717/77525590-9229a880-6e89-11ea-8c14-1d9a91f78e7f.png)

I tried a gink_test.zip which you attached to another issue #62  and produced the same crash and additionally a text file crash.txt:

UnhandledException

Oops, gInk crashed! Please include the following information if you plan to contact the developers:

Could not find a part of the path 'C:\Users\eszezol\Downloads\gInk_test\lang'.

Stack Trace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalGetFileDirectoryNames(String path, String userPathOriginal, String searchPattern, Boolean includeFiles, Boolean includeDirs, SearchOption searchOption)
   at System.IO.DirectoryInfo.GetFiles(String searchPattern, SearchOption searchOption)
   at System.IO.DirectoryInfo.GetFiles(String searchPattern)
   at gInk.Local.LoadLocalList() in C:\Geovens\gInk\src\Local.cs:line 80
   at gInk.Local..ctor() in C:\Geovens\gInk\src\Local.cs:line 74
   at gInk.Root..ctor() in C:\Geovens\gInk\src\Root.cs:line 50
   at gInk.Program.Main() in C:\Geovens\gInk\src\Program.cs:line 25

**Comment by geovens** [comment]
Hi szevzol, thanks for the report. It looks like gInk cannot find the folder "./lang", which is a folder with language files, so it crashed. For your first reported crash (with the normal version, not gInk_test.zip), how did you run gInk after you have downloaded it? Like did you move it somewhere before/after unzipping the downloaded file gInk_v1.0.7.zip?

Anyway, I will make a fix in next version so that, if the language file folder was not found at least the program could still work normally in English.

**Comment by szevzol** [comment]
What a quick response! ;)

I extracted it into the standard Downloads folder and started from there.

**Comment by geovens** [comment]
In your second reported crash (with gInk_test.zip), did you move the two files in gInk_test.zip to replace the two files of the same filename in the folder of normal version (presumably C:\Users\eszezol\Downloads\gInk_v1.0.7\), or did you simply run C:\Users\eszezol\Downloads\gInk_test\gInk.exe with only two files in that folder?

If you did the latter, please let me know what happens when you do the former.

**Comment by szevzol** [comment]
Can I use some workaround? E. g. creating lang folder manually?

**Comment by szevzol** [comment]
Just saw your last questions, Im going to check them.

**Comment by szevzol** [comment]
I did the latter, however not in the way I described first!

If I double click on gInk.exe in explorer window then app starts fine.

If I try to start it from the search results (Win + S then type gInk then Enter) then It crashes.

And no matter which gInk.exe is used.

**Comment by geovens** [comment]
I just pushed v1.0.8. You could try whether it works for you in both ways.

**Comment by szevzol** [comment]
I tried v1.0.8

Started from the extracted location is OK.
Started gInk.exe from the search results fails with the following crash message:

![image](https://user-images.githubusercontent.com/3088717/77540888-2bfe4f00-6ea4-11ea-97ee-c621493792a8.png)

But e.g. creating a shortcut on Desktop and starting that shortcut from the search results is OK.

**Comment by geovens** [comment]
I can't reproduce this bug on my computer so after my attempts to fix it I'm not able to verify I indeed fixed it. I made another fix according to your crash report. Could you try the following build?

[gInk_test_szevzol.zip](https://github.com/geovens/gInk/files/4381315/gInk_test_szevzol.zip)

**Comment by szevzol** [comment]
Now it seems only one backslash is missing ;)

![image](https://user-images.githubusercontent.com/3088717/77545635-03c61e80-6eab-11ea-9134-791c196a6e1b.png)

**Comment by geovens** [comment]
Ha, I wonder why the program behaves differently for you, maybe something related to the version of .NET framework? I don't know.... I hope someone with more insight of this specific issue could share their thoughts.

A new test build, yet again...

[gInk_test_szevzol_2.zip](https://github.com/geovens/gInk/files/4381499/gInk_test_szevzol_2.zip)

**Comment by szevzol** [comment]
Second fix works like a charm!

.Net versions:

$ ./DotNetVersions.exe
Currently installed "classic" .NET Versions in the system:
2.0.50727.4927 Service Pack 2
3.0.30729.4926 Service Pack 2
3.5.30729.4926 Service Pack 1
4.0.0.0
4.7.03190

**Comment by geovens** [comment]
Glad to hear that it works now. Thank you again for your report and your testing.

**Comment by Joeppie** [comment]
I believe this issue is caused by the _working directory_ being incorrectly set (or being relied on by the code). If so, the proper solution is to look up the ExecutingAssemblyLocation, retrieve it's folder location and then construct the relative path to the `lang` folder from there.
