### ISSUE TITLE
Prevent multiple instances

### ISSUE THREAD

**Issue by okayawright** [geovens/gInk#87]
feature request: do not allow to launch the program multiple times at once

Pull request here: #86

**Comment by pubpub-zz** [comment]
I've made an other proposal in my fork in order to start inking when an instance is already:
https://github.com/pubpub-zz/ppInk/commit/8c560c764be70b5e3c8d79e5f92b470ab199041a

**Comment by geovens** [comment]
Thank you okayawright!
