### ISSUE TITLE
request: adding stright line, square, arrow, counter

### ISSUE THREAD

**Issue by hungrysnake** [geovens/gInk#88]
Will you consider adding those annotation options to gInk to make it even better? I use it very often in teaching and gInk is definitely the tool I can't live without

**Comment by pubpub-zz** [comment]
Hi,
I produced a fork where those features have been introduced.I made a proposal to push back those changes but Geovens seemed to be not interested in. I've there fore change the name keeping history with gink.
Tell me if you like it 😃 
https://github.com/pubpub-zz/ppInk

**Comment by hungrysnake** [comment]
> Hi,
> I produced a fork where those features have been introduced.I made a proposal to push back those changes but Geovens seemed to be not interested in. I've there fore change the name keeping history with gink.
> Tell me if you like it 😃
> https://github.com/pubpub-zz/ppInk

@pubpub-zz amazing. it is exactly what I need. Just 2 comment to add. I will it to your repo.

**Comment by MarvinXu** [comment]
> Hi, I produced a fork where those features have been introduced.I made a proposal to push back those changes but Geovens seemed to be not interested in. I've there fore change the name keeping history with gink. Tell me if you like it 😃 https://github.com/pubpub-zz/ppInk

Is draw history supported?
